baseURL = "https://codepayne.com/"
languageCode = "en-gb"
title = "Code Payne"
theme = "bastet"
pluralizeListTitles = false
paginate = 10
pygmentsCodeFences = false
pygmentsUseClasses = false
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
description = "The personal blog and portfolio of an introverted Front-End Web Developer."
author = "Gonçalo Payne"
alias = "Bluefinger"
image = "img/code-payne-logo.svg"

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.renderer]
unsafe = true

[permalinks]
blog = "/:section/:year/:month/:title/"
portfolio = "/:section/:year/:title/"

[sitemap]
changefreq = "weekly"
priority = 0.5

# [[menu.main]]
# name = "Home"
# identifier = "home"
# url = "/"
# weight = -10
[[menu.main]]
name = "Portfolio"
identifier = "portfolio"
url = "/portfolio/"
weight = 10

[[menu.main]]
name = "Blog"
identifier = "blog"
url = "/blog/"
weight = 20
